- name: tomcat installation
  hosts: webservers
  become: yes

  tasks:
    - name: update yum package manager
      yum:
        name: '*'
        state: latest
        update_cache : yes

    - name: install dependent softwares
      yum:
        name:
          - java
          - git
        state: latest

    - name: create folder for Github repos
      file:
        state: directory
        path: /etc/ansible/GitHubReposDemo-mvn3.8.6
        owner: ec2-user
        mode: '0755'

    - name: clone github repo
      git:
        repo: 'https://github.com/pallem260497/Demo-mvn3.8.6.git'
        dest: /etc/ansible/GitHubRepos/Demo-mvn3.8.6/
    
    - name: install maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        

    - name: extract Maven
      unarchive:
        src: /opt/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        remote_src: yes
      

    - name: set java and maven Home paths
      ansible.builtin.blockinfile:
        path: /etc/profile.d/maven.sh
        create: yes
        owner: ec2-user
        group: ec2-user
        mode: '0777'
        block: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
          export M2_HOME=/opt/opt/apache-maven-3.8.6
          export MAVEN_HOME=/opt/opt/apache-maven-3.8.6
          export PATH=${M2_HOME}/bin:${PATH}
        

    - name: source maven.sh
      shell: source /etc/profile.d/maven.sh
      become_user: root

    - name: Creating a symlink
      ansible.builtin.file:
        src: /opt/apache-maven-3.8.6/bin/mvn
        dest: /usr/bin/mvn
        state: link

  
    - name: maven build
      command:  mvn clean package
      args:
        chdir: /etc/ansible/GitHubRepos/Demo-mvn3.8.6/
      become: yes
      
    
    - name: Ensure group "tomcat" exists
      group:
        name: tomcat
        state: present
        system : yes

    - name: Add the user 'tomcat' to group tomcat
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        system: yes  
        shell: /usr/bin/false 
        home: /usr/share/tomcat

    - name: tomcat downlaod
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /usr/share/
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: unarchive tomcat
      unarchive:
        src: /usr/share/apache-tomcat-9.0.65.tar.gz
        dest: /usr/share/tomcat
        owner: tomcat
        group: tomcat
        mode: "0755"
        remote_src: yes

    - name: Create Tomcat Systemd service
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/tomcat.service
        create: yes
        owner: tomcat
        group: tomcat
        mode: '0755'
        block: |
          [Unit]
          Description=Tomcat Server
          After=syslog.target network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat

          Environment=JAVA_HOME=/usr/lib/jvm/jre
          Environment='JAVA_OPTS=-Djava.awt.headless=true'
          Environment=CATALINA_HOME=/usr/share/tomcat/apache-tomcat-9.0.65
          Environment=CATALINA_BASE=/usr/share/tomcat/apache-tomcat-9.0.65
          Environment=CATALINA_PID=/usr/share/tomcat/apache-tomcat-9.0.65/temp/tomcat.pid
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M'
          ExecStart=/usr/share/tomcat/apache-tomcat-9.0.65/bin/catalina.sh start
          ExecStop=/usr/share/tomcat/apache-tomcat-9.0.65/bin/catalina.sh stop

          [Install]
          WantedBy=multi-user.target
    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: tomcat
        enabled: yes
        daemon_reload: yes

    - name: run the tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: started
        

    - name: copy artifact to tomcat
      copy:
        src: /etc/ansible/GitHubRepos/Demo-mvn3.8.6/target/mvnwebapp.war
        dest: /usr/share/tomcat/apache-tomcat-9.0.65/webapps/
        owner: tomcat
        group: tomcat
        mode: '0755'
        remote_src: yes

    - name: run the tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
